### PR TITLE
Allow setting configuration via environment variables

### PR DESCRIPTION
**Pull request by stanislaw55**
Hello MAXIV Kits team!

This is small enhancement that I crafted in no time but it will improve quality of my life a lot!

What I wanted to achieve: have both environment variables and command line options to provide configuration. Command line options have default values. This PR adds possibility to read value of environment variable in option. Precedence looks like this (from higher to lower precedence from left to right):
Command line > environment variable > default value

Hope you don't mind merging this little PR

### CODE REVIEW

**Review by AntoineDupre — APPROVED** [review]
Hello,

Looks great ! Good to see that we are not the only one using the gateway

**Comment by stanislaw55** [comment]
Hi @AntoineDupre 
I just started using it, will see what future will bring

**Comment by stanislaw55** [comment]
@AntoineDupre where should I report issues?

**Comment by AntoineDupre** [comment]
@stanislaw55 You can report issues on this repo, it is the most up to date

**Comment by stanislaw55** [comment]
@AntoineDupre Unfortunatelly, from my account 'issues' I do not see in this repository. Screenshot for reference
image
I do not know if this is something with permissions or my account

**Comment by AntoineDupre** [comment]
@stanislaw55 Fixed. (It seems that issues are disable by default on github forks)

**Comment by stanislaw55** [comment]
Thanks @AntoineDupre!

**Pull request merged**
